In [1]:
import tensorflow as tf

In [2]:
# create constant
hello_constant = tf.constant("Hello world")

with tf.Session() as sess:
    # run the hello_constant operation in session
    output = sess.run(hello_constant)
    print(output)

b'Hello world'


In [6]:
# placeholder
hello_plc = tf.placeholder(tf.string)

with tf.Session() as sess:
    output = sess.run(hello_plc, feed_dict={hello_plc: "hello world!"})
    print(output)

hello world!


In [9]:
# mat op

# Solution is available in the other "solution.py" tab
import tensorflow as tf

# TODO: Convert the following to TensorFlow:
x = 10
y = 2
z = x/y - 1

# TODO: Print z from a session
x_val = tf.placeholder(tf.int32)
y_val = tf.placeholder(tf.int32)
z = tf.subtract(tf.divide(x, y), 1)

with tf.Session() as sess:
    output = sess.run(z, feed_dict={x_val: x, y_val: y})
    print(output)

4.0


In [10]:
(-0.5*0.2)+(0.2*0.5)+(0.1*0.6) + 0.1

0.16

In [11]:
(0.7*0.2)+(-0.8*0.5)+(0.2*0.6)+0.2

0.06

In [15]:
# varialbe initialization

n_labels = 5
n_features = 120

w = tf.Variable( tf.truncated_normal((n_features, n_labels)) )
b = tf.Variable( tf.zeros(n_labels) )

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    w_val = sess.run(w)
    b_val = sess.run(b)
    print(w_val, b_val)

[[-1.14720881 -1.06811249  0.56588781 -0.48987883  0.07365284]
 [-1.1785531  -0.71192408  0.7692486  -0.46188197  0.2695438 ]
 [ 0.73087186 -0.73941332  0.15402493  0.13255326 -1.71802151]
 [-0.0907177  -1.01854718  0.00297385 -0.26871216 -0.27680004]
 [ 0.82719791 -1.81959105  0.35158837  0.86775029 -1.36531663]
 [-0.2804963  -0.2730858   0.49527058 -0.51121968 -1.48289609]
 [-1.09408903 -0.08977143 -0.40364632  0.44308501 -0.03766533]
 [-1.26364303 -0.39622983 -0.64745587  0.38616782  0.36625981]
 [-0.05364626 -0.46884286  0.66116273 -0.75877118 -0.65021569]
 [-1.1838882   0.37877956  0.68408173  0.47780088 -0.95781666]
 [-0.49219719  0.32340738  1.30900514 -0.11479758 -0.58683276]
 [ 0.71128333 -0.65259123  0.67349821 -0.0226678  -1.21102333]
 [-0.40837121 -0.87073565  0.69359863 -0.72143668 -0.76847309]
 [-0.13793062  1.07325852  0.33266068  1.02208614 -0.1897779 ]
 [-1.18983555 -1.62085712  0.40976363 -0.24412751 -0.60769868]
 [ 0.92667359 -0.8044495   0.81873059  1.98325574 -0.68