In [ ]:
# Solution is available in the other "solution.py" tab
import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    return np.exp(x) / np.sum(np.exp(x), axis=0)
 
logits = np.array([0.2, 0.1, 0.001])
print(softmax(logits))

[ 0.36705501  0.3321251   0.30081989]


In [129]:
logits = np.array([
    [1, 2, 5, 1],
    [2, 4, 1, 6],
    [3, 8, 2, 6]])


sumsY = np.sum(logits, axis=0)
sumsX = np.sum(logits, axis=1)

print(sumsY)
print(sumsX)


[ 6 14  8 13]
[ 9 13 19]
